version: '3.9'
services:
  gateway:
    build: ./gateway
    ports: ["3000:3000"]
    environment:
      - NODE_ENV=development
    depends_on: [upstream1, upstream2]

  upstream1:
    build: ./upstream-mock
    environment:
      - PORT=4001
      - SERVICE_NAME=upstream-1
      - FAIL_RATE=0.05
    ports: ["4001:4001"]

  upstream2:
    build: ./upstream-mock
    environment:
      - PORT=4002
      - SERVICE_NAME=upstream-2
      - FAIL_RATE=0.02
    ports: ["4002:4002"]
