version: '3.9'

services:
  gateway:
    build: ./gateway
    ports: ["3000:3000"]
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://pulse:pulse@postgres:5432/pulseapi
      - JWT_SECRET=supersecretjwtkey123
      - ADMIN_KEY=admin-secret-key
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./gateway/config.json:/app/config.json
    restart: unless-stopped

  upstream1:
    build: ./upstream-mock
    environment: [PORT=4001, SERVICE_NAME=upstream-1, FAIL_RATE=0.05]
    ports: ["4001:4001"]

  upstream2:
    build: ./upstream-mock
    environment: [PORT=4002, SERVICE_NAME=upstream-2, FAIL_RATE=0.02]
    ports: ["4002:4002"]

  upstream3:
    build: ./upstream-mock
    environment: [PORT=4003, SERVICE_NAME=upstream-3, FAIL_RATE=0.0]
    ports: ["4003:4003"]

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  postgres:
    image: postgres:15-alpine
    environment: [POSTGRES_USER=pulse, POSTGRES_PASSWORD=pulse, POSTGRES_DB=pulseapi]
    ports: ["5432:5432"]
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pulse -d pulseapi"]
      interval: 5s
      timeout: 3s
      retries: 10

  dashboard:
    build: ./dashboard
    ports: ["5173:80"]
    depends_on: [gateway]

  jaeger:
    image: jaegertracing/all-in-one:1.52
    ports:
      - "16686:16686"   # Jaeger UI
      - "14268:14268"   # HTTP collector
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  prometheus:
    image: prom/prometheus:v2.48.0
    ports:
      - "9090:9090"     # Prometheus UI + query API
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=7d'
      - '--web.enable-lifecycle'   # allows POST /-/reload to hot-reload config
    depends_on: [gateway]
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.2.2
    ports:
      - "3001:3000"     # Grafana UI (3000 is taken by gateway)
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=pulse
      - GF_AUTH_ANONYMOUS_ENABLED=true      # lets you view dashboards without login
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on: [prometheus]
    restart: unless-stopped

volumes:
  pg_data:
  prometheus_data:
  grafana_data:
